// Automatically generated by MockGen. DO NOT EDIT!
// Source: src/github.com/lordbyron/auto-spf-flattener/dns/dns.go

package mock_dns

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of DNSAPI interface
type MockDNSAPI struct {
	ctrl     *gomock.Controller
	recorder *_MockDNSAPIRecorder
}

// Recorder for MockDNSAPI (not exported)
type _MockDNSAPIRecorder struct {
	mock *MockDNSAPI
}

func NewMockDNSAPI(ctrl *gomock.Controller) *MockDNSAPI {
	mock := &MockDNSAPI{ctrl: ctrl}
	mock.recorder = &_MockDNSAPIRecorder{mock}
	return mock
}

func (_m *MockDNSAPI) EXPECT() *_MockDNSAPIRecorder {
	return _m.recorder
}

func (_m *MockDNSAPI) FilterTXTRecords(_param0 string, _param1 string) ([]string, error) {
	ret := _m.ctrl.Call(_m, "FilterTXTRecords", _param0, _param1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDNSAPIRecorder) FilterTXTRecords(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FilterTXTRecords", arg0, arg1)
}

func (_m *MockDNSAPI) GetTXTRecordContent(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetTXTRecordContent", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDNSAPIRecorder) GetTXTRecordContent(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetTXTRecordContent", arg0)
}

func (_m *MockDNSAPI) WriteTXTRecord(_param0 string, _param1 string) (string, error) {
	ret := _m.ctrl.Call(_m, "WriteTXTRecord", _param0, _param1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDNSAPIRecorder) WriteTXTRecord(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WriteTXTRecord", arg0, arg1)
}

func (_m *MockDNSAPI) UpdateTXTRecord(_param0 string, _param1 string, _param2 string) (string, error) {
	ret := _m.ctrl.Call(_m, "UpdateTXTRecord", _param0, _param1, _param2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDNSAPIRecorder) UpdateTXTRecord(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateTXTRecord", arg0, arg1, arg2)
}

func (_m *MockDNSAPI) DeleteTXTRecord(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteTXTRecord", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockDNSAPIRecorder) DeleteTXTRecord(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteTXTRecord", arg0)
}
